=== CentralLabFacilities/bonsai/bonsai_tutorials/src/main/config/bonsai_configs/BonsaiConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="option">
		<xsd:simpleContent>
			<xsd:extension base="xsd:string">
				<xsd:attribute name="key" type="xsd:string" />
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>

	<xsd:complexType name="options">
		<xsd:sequence>
			<xsd:element name="Option" type="option" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="factoryoptions">
		<xsd:complexContent>
			<xsd:extension base="options">
				<xsd:attribute name="factoryClass" type="xsd:string" />
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<!-- TODO this also needs an interface for complete middleware decoupling 
		that can default to the standard sensor interface -->
	<xsd:complexType name="sensor">
		<xsd:sequence>
			<xsd:element name="Options" type="options" minOccurs="0"
						 maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="key" type="xsd:string" use="required" />
		<xsd:attribute name="dataTypeClass" type="xsd:string"
					   use="required" />
		<xsd:attribute name="listTypeClass" type="xsd:string"
					   use="optional" />
		<xsd:attribute name="factoryClass" type="xsd:string"
					   use="required" />
		<xsd:attribute name="sensorClass" type="xsd:string" use="required" />
		<xsd:attribute name="wireTypeClass" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="sensorSource">
		<xsd:attribute name="src" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="actuator">
		<xsd:sequence>
			<xsd:element name="Options" type="options" minOccurs="0"
						 maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="key" type="xsd:string" use="required" />
		<xsd:attribute name="factoryClass" type="xsd:string"
					   use="required" />
		<xsd:attribute name="actuatorClass" type="xsd:string"
					   use="required" />
		<xsd:attribute name="actuatorInterface" type="xsd:string"
					   use="required" />
	</xsd:complexType>

	<xsd:complexType name="actuatorSource">
		<xsd:attribute name="src" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="slots">
		<xsd:sequence>
			<xsd:element name="Slot" type="slot" minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="slot">
		<xsd:attribute name="dataTypeClass" type="xsd:string"
					   use="required" />
		<xsd:attribute name="slotClass" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="workingmemory">
		<xsd:sequence>
			<xsd:element name="Options" type="options" minOccurs="0"
						 maxOccurs="1" />
			<xsd:element name="Slots" type="slots" minOccurs="0"
						 maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="key" type="xsd:string" use="required" />
		<xsd:attribute name="factoryClass" type="xsd:string"
					   use="required" />
		<xsd:attribute name="workingMemoryClass" type="xsd:string"
					   use="required" />
	</xsd:complexType>

	<xsd:complexType name="workingmemorySource">
		<xsd:attribute name="src" type="xsd:string" use="required" />
	</xsd:complexType>

	<xsd:complexType name="coordinatetransformer">
		<xsd:attribute name="factoryClass" type="xsd:string"
					   use="required" />
		<xsd:attribute name="coordinateTransformerClass" type="xsd:string"
					   use="required" />
	</xsd:complexType>


	<xsd:element name="BonsaiConfiguration">

		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="FactoryOptions" type="factoryoptions"
							 minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="CoordinateTransformer" type="coordinatetransformer"
							 minOccurs="0" maxOccurs="1" />
				<xsd:element name="WorkingMemories" type="workingmemorySource"
							 minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="WorkingMemory" type="workingmemory"
							 minOccurs="0" maxOccurs="unbounded" />
				<xsd:element name="Sensors" type="sensorSource" minOccurs="0"
							 maxOccurs="unbounded" />
				<xsd:element name="Sensor" type="sensor" minOccurs="0"
							 maxOccurs="unbounded" />
				<xsd:element name="Actuators" type="actuatorSource" minOccurs="0"
							 maxOccurs="unbounded" />
				<xsd:element name="Actuator" type="actuator" minOccurs="0"
							 maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>

		<xsd:unique name="uniqueFactoryOptions">
			<xsd:selector xpath="FactoryOptions" />
			<xsd:field xpath="@className" />
		</xsd:unique>

		<xsd:unique name="uniqueWorkingMemoryOptions">
			<xsd:selector xpath="WorkingMemoryOptions" />
			<xsd:field xpath="@className" />
		</xsd:unique>

		<xsd:unique name="uniqueSensors">
			<xsd:selector xpath="Sensor" />
			<xsd:field xpath="@key" />
		</xsd:unique>

		<xsd:unique name="uniqueActuators">
			<xsd:selector xpath="Actuator" />
			<xsd:field xpath="@key" />
		</xsd:unique>

		<xsd:unique name="uniqueMemories">
			<xsd:selector xpath="WorkingMemory" />
			<xsd:field xpath="@key" />
		</xsd:unique>

	</xsd:element>

</xsd:schema>

=== CentralLabFacilities/bonsai/bonsai_tutorials/src/main/config/bonsai_configs/minimalConfig.xml
<?xml version="1.0" encoding="utf-8"?>

<BonsaiConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="BonsaiConfiguration.xsd">
    
    <FactoryOptions factoryClass="de.unibi.citec.clf.bonsai.ros.RosFactory" />
    <FactoryOptions factoryClass="de.unibi.citec.clf.bonsai.ros2.Ros2Factory" />
    <FactoryOptions factoryClass="de.unibi.citec.clf.bonsai.memory.MemoryFactory" />

    <CoordinateTransformer factoryClass="de.unibi.citec.clf.bonsai.ros.RosFactory"
                           coordinateTransformerClass="de.unibi.citec.clf.bonsai.ros.TFTransformer"
    />
    
    <WorkingMemory key="WorkingMemory"
                   factoryClass="de.unibi.citec.clf.bonsai.memory.MemoryFactory"
                   workingMemoryClass="de.unibi.citec.clf.bonsai.memory.DefaultMemory">
    </WorkingMemory>

    <Sensor key="Ros1StringSensor" dataTypeClass="java.lang.String"
            factoryClass="de.unibi.citec.clf.bonsai.ros.RosFactory"
            sensorClass="de.unibi.citec.clf.bonsai.ros.sensors.RosStringSensor"
            wireTypeClass="std_msgs.String">
        <Options>
            <Option key="topic">/ros1/in</Option>
        </Options>
    </Sensor>

    <Sensor key="Ros2StringSensor" dataTypeClass="java.lang.String"
            factoryClass="de.unibi.citec.clf.bonsai.ros2.Ros2Factory"
            sensorClass="de.unibi.citec.clf.bonsai.ros2.sensors.StringSensor"
            wireTypeClass="id.jrosmessages.std_msgs.StringMessage">
        <Options>
            <Option key="topic">/ros2/in</Option>
        </Options>
    </Sensor>

    <Actuator key="Ros1StringAct" factoryClass="de.unibi.citec.clf.bonsai.ros.RosFactory"
              actuatorClass="de.unibi.citec.clf.bonsai.ros.actuators.RosStringActuator"
              actuatorInterface="de.unibi.citec.clf.bonsai.actuators.StringActuator">
        <Options>
            <Option key="topic">/ros1/out</Option>
        </Options>
    </Actuator>

    <Actuator key="Ros2StringAct" factoryClass="de.unibi.citec.clf.bonsai.ros2.Ros2Factory"
              actuatorClass="de.unibi.citec.clf.bonsai.ros2.actuators.RosStringActuator"
              actuatorInterface="de.unibi.citec.clf.bonsai.actuators.StringActuator">
        <Options>
            <Option key="topic">/ros2/out</Option>
        </Options>
    </Actuator>



</BonsaiConfiguration>
